version: 0.2

phases:
  pre_build:
    commands:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build .
  post_build:
    commands:
