version: '3.2'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: suyc
      MYSQL_USER: suyc
      MYSQL_PASSWORD: suyc
      MYSQL_DATABASE: suyc
    ports:
      - "3306:3306"
  migrator:
    build: ../speedupamerica-migrator
    env_file:
      - local.env
    command: ["rake", "db:migrate"]
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ../speedupamerica-migrator:/migrator
  frontend:
    build: .
    env_file:
      - local.env
    ports:
      - "3000:3000"
    volumes:
      - ./app:/suyc/app
      - ./config:/suyc/config
      - ./data:/suyc/data
      - ./lib:/suyc/lib
      - ./log:/suyc/log
      - ./public:/suyc/public
  notebooks:
    build:
      context: ./notebooks
    depends_on:
      - mysql
    ports:
      - 8888:8888
    env_file:
      - local.env
    volumes:
      - ./data:/home/jovyan/data/
      - ./notebooks:/home/jovyan/
